# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ipc.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'ipc.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\tipc.proto\x12\x0f\x65lpis.telemetry\"[\n\x10\x45valuationMetric\x12\x0c\n\x04step\x18\x01 \x01(\x04\x12\r\n\x05\x65poch\x18\x02 \x01(\x02\x12\x1c\n\x14\x65xact_match_accuracy\x18\x03 \x01(\x02\x12\x0c\n\x04loss\x18\x04 \x01(\x02\x32\x66\n\tTelemetry\x12Y\n\rStreamMetrics\x12!.elpis.telemetry.EvaluationMetric\x1a!.elpis.telemetry.EvaluationMetric(\x01\x30\x01\x42\x0eZ\x0clumen/protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'ipc_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\014lumen/protos'
  _globals['_EVALUATIONMETRIC']._serialized_start=30
  _globals['_EVALUATIONMETRIC']._serialized_end=121
  _globals['_TELEMETRY']._serialized_start=123
  _globals['_TELEMETRY']._serialized_end=225
# @@protoc_insertion_point(module_scope)
