# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ipc_pb2 as ipc__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in ipc_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TelemetryStub(object):
    """── Service Definitions ──────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamMetrics = channel.stream_stream(
                '/elpis.telemetry.Telemetry/StreamMetrics',
                request_serializer=ipc__pb2.EvaluationMetric.SerializeToString,
                response_deserializer=ipc__pb2.EvaluationMetric.FromString,
                _registered_method=True)


class TelemetryServicer(object):
    """── Service Definitions ──────────────────────────────────────────

    """

    def StreamMetrics(self, request_iterator, context):
        """Stream evaluation metrics in real-time during training.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TelemetryServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamMetrics': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamMetrics,
                    request_deserializer=ipc__pb2.EvaluationMetric.FromString,
                    response_serializer=ipc__pb2.EvaluationMetric.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'elpis.telemetry.Telemetry', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('elpis.telemetry.Telemetry', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Telemetry(object):
    """── Service Definitions ──────────────────────────────────────────

    """

    @staticmethod
    def StreamMetrics(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/elpis.telemetry.Telemetry/StreamMetrics',
            ipc__pb2.EvaluationMetric.SerializeToString,
            ipc__pb2.EvaluationMetric.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
